### ISSUE TITLE
Don't select a default project at startup

### ISSUE THREAD

**Issue by baali** [baali/bw_projects#17]
> No project is selected automatically at startup (i.e. default is not created and selected automatically). projects.current can be None

Based on this [documentation](https://github.com/baali/bw_projects/blob/478fe895eff6d19565cb999b03a434563c621534/README.md#changes-versus-brightway2)

**Comment by baali** [comment]
@cmutel I am following the [example](https://github.com/baali/bw_projects#bw_projects) and I have a few doubts on how this change will impact other APIs for `ProjectManager`:

1. Existing property `dir` and `logs_dir` relies on `self.current`. How should they behave when `self.current is None`? Should they raise an `Error`?
2. `copy_project` can't be used without we first call `set_current`. In existing scenario, it will copy `default`.

**Comment by cmutel** [comment]
> Existing property dir and logs_dir relies on self.current. How should they behave when self.current is None? Should they raise an Error?

A good question! Given our user base, I think raising a custom error (`NoProjectSelected`?) is the better choice, as otherwise I am sure that some beginner users will not check `is None` and run into trouble later on and get discouraged.

> copy_project can't be used without we first call set_current. In existing scenario, it will copy default.

I think this is fine, we can raise the same error.
